return {}
-- { -- Add indentation guides even on blank lines
-- 	"lukas-reineke/indent-blankline.nvim",
-- 	-- Enable `lukas-reineke/indent-blankline.nvim`
-- 	-- See `:help ibl`
-- 	main = "ibl",
-- 	opts = {},
-- 	{
-- 		"nvim-neo-tree/neo-tree.nvim",
-- 		version = "*",
-- 		dependencies = {
-- 			"nvim-lua/plenary.nvim",
-- 			"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
-- 			"MunifTanjim/nui.nvim",
-- 		},
-- 		cmd = "Neotree",
-- 		keys = {
-- 			{ "\\", ":Neotree reveal<CR>", desc = "NeoTree reveal", silent = true },
-- 		},
-- 		opts = {
-- 			filesystem = {
-- 				filtered_items = {
-- 					visible = true,
-- 					hide_dotfiles = false,
-- 					hide_gitignored = false,
-- 					never_show = { ".git", "node_modules" }, -- Exclude .git and node_modules folders
-- 					always_show = { ".env" }, -- Always show .env file
-- 				},
-- 				follow_current_file = {
-- 					enabled = true, -- Focus on the current file when changing buffers
-- 				},
-- 				window = {
-- 					mappings = {
-- 						["\\"] = "close_window",
-- 					},
-- 				},
-- 			},
-- 		},
-- 	},
-- }
